### ISSUE TITLE
aausidebar AAU logo goes above slide

### ISSUE THREAD

**Issue by eyJhb** [jkjaer/aauLatexTemplates#1]
When using the aausidebar for beamer, the logo will go above the slide, which for me does not seem like it should. 

Could this be changed?

**Comment by jkjaer** [comment]
The logo does not go above the slide, only the top of the grey circle, and this is on purpose.

If you want to change the behaviour locally, you should modify the \AAUheaderbackground command in the beamerouterthemeAAUsidebar.sty file.

**Comment by eyJhb** [comment]
@jkjaer as long as it's on purpose, it is fine. Just wanted to make sure that it was.
