### ISSUE TITLE
Using natbib in aauPhdCollectionThesis

### ISSUE THREAD

**Issue by mlindsk** [jkjaer/aauLatexTemplates#14]
Hi,

First of all. Thanks for sharing this template! I just want to share my five cents. I spent quite some time figuring out why I couldn't make it work with natbib. I added `\usepackage{natbib}` in `preamble.tex` and removed `\usepackage{cite}`. Then, in `macros.tex` i changed `\bibliographystyle{IEEEtran}` to `\bibliographystyle{apalike}`. It gave me a bunch of troubles until I realized, that the [introduction file](https://github.com/jkjaer/aauLatexTemplates/blob/master/aauPhdCollectionThesis/introduction/introduction.tex) contains the hardcoded bibliographystyle: `{\small\bibliographystyle{IEEEtranS}\bibliography{bib/mybib}}`. In the paper files the new command [\defaultbib](https://github.com/jkjaer/aauLatexTemplates/blob/master/aauPhdCollectionThesis/setup/macros.tex) is used.

Maybe `{\small\bibliographystyle{IEEEtranS}\bibliography{bib/mybib}}` should have a new command located in `macros.tex` as well.

/Mads

**Comment by jkjaer** [comment]
Sorry for the long response time. Unfortunately, I did not receive any email notification. 

Thanks for your suggestion. I will take a look at it asap.

**Comment by jkjaer** [comment]
I have now done the following:
- Introduced a macro called \introbib specifying the bibliography in the introduction as you suggested
- Renamed the \defaultbib into \papersbib
Thanks a lot for your suggestions!

**Comment by mlindsk** [comment]
Thanks - much appreciated!
