### ISSUE TITLE
Standalone package - texmf

### ISSUE THREAD

**Issue by eyJhb** [jkjaer/aauLatexTemplates#2]
Would it be possible, to convert the individual files from the beamer templates, into a package that can be used directly inside the ~/texmf folder.
I know there has previously been a way, and I'm currently using it, so I don't have to duplicate the files, but rather just "install" the .sty files once.

But there is one problem, the AAUgraphics still needs to be inside the same folder, as the beamer .tex file.
Anyway that those could be included inside ~/texmf ?

This would open up for the possibility of using pandoc, and creating AAU templates.

**Comment by jkjaer** [comment]
I am not sure how you would make such a single package. Instead, I think you could use the \graphicspath command inside the master document to point to a directory where you store the AAUgraphics.

**Comment by eyJhb** [comment]
Could the installation directory come back, where it specified you could put it in ~/texmf ?
Because I just found this - https://tex.stackexchange.com/a/12991

This means, AAUgraphics could be in ~/texmf/tex/generic/images and would be able to compile, without it being inside the same folder as master.tex, which would solve this issue.

Any thoughts?

**Comment by jkjaer** [comment]
I guess that would work, but it would not be an elegant solution to have multiple versions of the same files in the same repository (i.e. maintaining a local and global installation directory). Instead, I think a better solution would be an 'install' script that would copy the files and images to the correct places in the ~/texmf folder. Of course, the script should work on multiple platforms (Linux, Windows, etc.).

Unfortunately, I do not have time to look into that now. However, if you have the time and skills to do it, I will include it here.

**Comment by eyJhb** [comment]
I think the solution would be to have a styles directory, which contains all the .sty files (and graphics), and then have a install.sh (linux. mac) and a install.bat (windows).

This would remove duplication files and clean up the examples folders - which would be a good thing in my opinion.

**Comment by jkjaer** [comment]
When you write 'all the .sty files', do you then mean a folder/template or a folder for all/beamer files?

Anyway, I think your plan sounds good, but I would prefer that every template is written as an example so that people have a starting point which works. A lot of people using the templates are not latex-savvy, and they just want something that works.

Would you be interested in being added as a collaborator on the repository?

**Comment by eyJhb** [comment]
Hmm.. I see your point, but that would require that instead of making a resources folder like shown below, the install scripts points to the .sty files inside all the examples, and creates the structure needed in texmf.

It would simplify it for anyone new without experience, but clutters up the examples.
I would go for doing in the resources way, since if you are already in for installing LaTeX, copying a folder should be easy

## Example directory listing
```
aauBeamer/
aauPhdCollectionThesis/
aauPoster/
aauReportTemplate/
img/
resources/
    - texmf/
install.bat
install.sh
LICENSE
README.md
```

About collaborator, that is totally up to you. I wouldn't be against it! :)

**Comment by jkjaer** [comment]
Sorry for the late reply. I will add you as a collaborator asap.

After answering numerous emails from users of the templates, I have found that you cannot simply assume that users can do that. A lot of people also use latex in the cloud so that they do not have to install it. Finally, if you want to structure the resources folder as the texmf folder, then for a beamer theme you have to extract four different .sty files from four different folders (theme, outer, inner, and color) + the pictures to compile an example.

For all these reasons, I would clearly prefer to keep the examples folders as-is and then have the install scripts create the texmf folder and copy it to the correct path.

**Comment by eyJhb** [comment]
Thanks! I'll create a branch to work in then ! :)

I fully understand that, I have not dealt with all those e-mails, so I might have been too oblivious to the problems that might occur. And would have figured that online editors supported importing packages yourself.

I'll and see what I can do, and then make a PR you can approve, before merging with the master branch.

**Comment by jkjaer** [comment]
Great, thanks a lot!

**Comment by eyJhb** [comment]
@jkjaer what is you primary OS? The current install.sh should work for Linux and Mac, but I cannot test it for Mac. 

Will work on Windows next - .bat :)

**Comment by jkjaer** [comment]
Great. Thanks for the update.

I'm afraid, my primary OS is linux, and I do not own a Mac :/

**Comment by eyJhb** [comment]
@jkjaer  been way to busy, but am hoping for some free time now, to finish the script!

I do have one notes though, and that is, that currently there is no "single" way, that the graphics are kept, and therefore they search for them in different directories.
```
aauReportTemplate
- figures
aauPoster
- <root>
aauBeamer
- AAUgraphics
```
So instead of just having a single folder in `~textmf/tex/generic/images` called AAUgraphics, 2 folders and a bunch of files are needed.

Would it be okay with you, if a separate pull request where made, so that graphics will always be located in a AAUgraphics folder?

Currently the structure looks like this
```
AAUgraphics/
aau_logo_new.eps
aau_logo_new_neg.eps
aau_logo_new_neg.pdf
aau_logo_new.pdf
figures/
```

**Comment by jkjaer** [comment]
No worries. It is done when it is done :)

Yes, you are right about that I have been inconsistent with how I have organised the AAU graphics. I think your suggested structure is good so please go ahead.

**Comment by eyJhb** [comment]
It should be ready for Linux now, but Windows is a whole other story...
No idea how long that will take...

Will give it a shot when I got time, but we might have to consider not doing windows support, since Windows texmf moves around quite a lot (as far as I can gather).

**Comment by jkjaer** [comment]
Thanks for all your work!

It is fine with me if we do not have Windows support, but it would of course be nice if we had it. However, I guess we can always include later.

**Comment by eyJhb** [comment]
Closing because of merge.
