### ISSUE TITLE
install.sh: script does not work on OSX

### ISSUE THREAD

**Issue by eyJhb** [jkjaer/aauLatexTemplates#5]
Currently the installation script does not work on OSX, as it does not copy the images correctly.

The first problem is that OSX copies all the files inside the folder using `cp -R /tmp/files/ /dst/`, where I would expect it to copy the folder but it copies the files INSIDE...

Secondly, it does not respect the generic images folder, as it does not look inside the textmf folder...
So we either need to find the path where OSX looks for images, or print a statement saying that it is `unable to install images`.

**Comment by eyJhb** [comment]
On the bright side, it has worked perfectly without any hiccups on all Linux installations I have tried. I will research this bug and try to find a solution, when I have the time.

@jkjaer you used Linux and not OSX right?

**Comment by jkjaer** [comment]
Thanks, @eyJhb. Yes, I use Linux, and have never used OSX.

**Comment by eyJhb** [comment]
Fixed in #6
