### ISSUE TITLE
Correct AAU Blue colors

### ISSUE THREAD

**Issue by eyJhb** [jkjaer/aauLatexTemplates#7]
I know one of my mates from my study does some work every semester, fixing up the colors so they match the AAU standards, maybe he would look at it.

I will try to ping him to this. 

I think this includes ...
- Code environments
- Figure text
- Table headers/borders (?)

But I am hoping he could clarify it.

**Comment by jkjaer** [comment]
I thought I had already matched the colours to the AAU standard, but maybe they have changed it? Anyway, I am looking forward to hearing what your mate has to say :)

**Comment by eyJhb** [comment]
I think it is for additional environments, but hoping he can clarify it better!

But I am guessing he is currently jet lagged, so hoping Thursday :)

**Comment by Lanestolen** [comment]
It would be nice with additional environments allowing people to create their own color palette in the report :)
Allowing them to style table headers and code environments, simply by defining the color in one place.

**Comment by jkjaer** [comment]
I am not completely sure of what you mean. Could you give an example? If I wanted to change, e.g., the colours in the table and figure captions, I can already do that in the preamble via \captionsetup{...}. The same goes for chapter and section headings (\titleformat{...}).

**Comment by eyJhb** [comment]
I think we will just close this again, until there is something specific that can be put into a PR... :)
